name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=20.3.3
  - pyarrow=2.0
  - numpy=1.22.4
  - pip:
      - wandb==0.10.21
      - six==1.16.0
      - protobuf==3.20.1